export type {
  HeaderNavChildItem,
  HeaderNavItem,
  HeaderRightItem,
  ColorModeConfig,
  HtmlPreviewConfig,
  LocaleConfig,
  VersionConfig,
  FooterConfig,
  FrontmatterPreviewConfig,
  BodyFootUtilAreaConfig,
  TagPlacement,
  TagGovernanceMode,
  TagVocabularyEntry,
  MetaTagsConfig,
} from './settings-types';
import type {
  HeaderNavItem,
  HeaderRightItem,
  ColorModeConfig,
  HtmlPreviewConfig,
  LocaleConfig,
  VersionConfig,
  FooterConfig,
  FrontmatterPreviewConfig,
  BodyFootUtilAreaConfig,
  TagPlacement,
  TagGovernanceMode,
  MetaTagsConfig,
} from './settings-types';

export const settings = {
  colorScheme: 'Default Dark',
  colorMode: {
    defaultMode: 'dark',
    lightScheme: 'Default Light',
    darkScheme: 'Default Dark',
    respectPrefersColorScheme: true,
  } satisfies ColorModeConfig as ColorModeConfig | false,
  siteName: 'zmanuals doc',
  siteDescription:
    'Architecture, design system, and infrastructure notes for the takazudomodular manual viewer' as string,
  base: '/',
  trailingSlash: false as boolean,
  noindex: true as boolean,
  editUrl: false as string | false,
  githubUrl: 'https://github.com/Takazudo/takazudomodular-manuals' as string | false,
  siteUrl: 'https://doc-manuals.takazudomodular.com' as string,
  metaTags: {
    description: true,
    keywords: false,
    ogImage: '/img/ogp.png',
    ogSiteName: true,
    twitterCard: 'summary_large_image',
    twitterCreator: '@Takazudo',
  } satisfies MetaTagsConfig as MetaTagsConfig,
  docsDir: 'src/content/docs',
  defaultLocale: 'en' as const,
  locales: {} as Record<string, LocaleConfig>,
  mermaid: true,
  sitemap: false,
  docMetainfo: false,
  docTags: false,
  tagPlacement: 'after-title' as TagPlacement,
  tagGovernance: 'off' as TagGovernanceMode,
  tagVocabulary: false as boolean,
  frontmatterPreview: false as FrontmatterPreviewConfig | false,
  llmsTxt: false,
  math: false,
  cjkFriendly: true as boolean,
  onBrokenMarkdownLinks: 'warn' as 'warn' | 'error' | 'ignore',
  aiAssistant: false as boolean,
  aiChatDemoMode: false as boolean,
  aiChatAllowedOrigins: [] as string[],
  aiChatGlobalDailyLimit: false as number | false,
  docHistory: true,
  bodyFootUtilArea: {
    docHistory: true,
    viewSourceLink: false,
  } satisfies BodyFootUtilAreaConfig as BodyFootUtilAreaConfig | false,
  designTokenPanel: false as boolean,
  tocMinDepth: 2 as number,
  tocMaxDepth: 4 as number,
  headingIdStrategy: 'hierarchical' as 'flat' | 'hierarchical',
  sidebarResizer: true as boolean,
  sidebarToggle: true as boolean,
  imageEnlarge: true as boolean,
  htmlPreview: undefined as HtmlPreviewConfig | undefined,
  versions: false as VersionConfig[] | false,
  claudeResources: {
    // doc/ is a subdirectory; .claude lives at the repo root one level up
    claudeDir: '../.claude',
  } as { claudeDir: string; projectRoot?: string } | false,
  defaultLocaleOnlyPrefixes: [
    '/docs/claude-md/',
    '/docs/claude-skills/',
    '/docs/claude-agents/',
    '/docs/claude-commands/',
  ] as string[],
  // Opt-in: preset injects package-owned routes (/404, /sitemap.xml, /robots.txt, etc.).
  // Without this, the preset adds zero routes → empty injected site.
  packageOwnedRoutes: true,
  footer: false as FooterConfig | false,
  headerNav: [
    { label: 'Architecture', path: '/docs/architecture', categoryMatch: 'architecture' },
    { label: 'Design System', path: '/docs/design-system', categoryMatch: 'design-system' },
    { label: 'Infrastructure', path: '/docs/infrastructure', categoryMatch: 'infrastructure' },
  ] satisfies HeaderNavItem[] as HeaderNavItem[],
  headerRightItems: [
    { type: 'component', component: 'github-link' },
    { type: 'component', component: 'theme-toggle' },
    { type: 'component', component: 'search' },
  ] satisfies HeaderRightItem[] as HeaderRightItem[],
};
